version: "2"
services:
  app:
    image: busybox
    container_name: 2s_app
    depends_on:
      - "nginx"

  data:
    image: busybox
    container_name: 2as_data
    volumes:
      - .:/var/www

  nginx:
    image: nginx:latest
    container_name: 2as_nginx
    volumes_from:
      - data
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: 2amigos.test
      NGINX_HTTP_PORT: 80
      NGINX_HTTPS_PORT: 443
      NGINX_CLIENT_MAX_BODY_SIZE: 10m
      NGINX_VHOST_ROOT_DIRECTORY: /var/www/public
      FASTCGI_URL: php
    depends_on:
      - "php"

  php:
    image: php:7.4-fpm
    container_name: 2as_php
    volumes_from:
      - data
    depends_on:
      - "db"
    working_dir: /var/www
    environment:
      DB_DRIVER: pdo_mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: 2as_test
      DB_USER: 2as_user
      DB_PASSWORD: 2as_password

  db:
    image: mysql:5.7.19
    container_name: 2as_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 2as_user
      MYSQL_PASSWORD: 2as_password
      MYSQL_DATABASE: 2as_test
